version: '1.0'
services:
  jupyter-lab:
    build: .
    ports:
      - "8888:8888"
    privileged: true
    volumes:
      - ./tf-msp:/tf-msp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]